### PR TITLE
Update doc

### PR DESCRIPTION
**Pull request by theofidry**

### CODE REVIEW

**Comment by bamarni** [comment]
I understand that phpunit might not be the best to promote, but the ones you're suggesting are not that much popular for a readme example imo. What about behat and php-cs-fixer? (Usually behat is used through something like selenium / phantomjs so the code is not loaded directly).

**Comment by theofidry** [comment]
Why not, I can't find any good example why perfectly fits the good practices I want to promote so I'll have to compromise somewhere :P Let's stick to the examples you gave or behat & php-cs-fixer.

**Comment by bamarni** [comment]
Do you still want to change it to behat and php-cs-fixer? Otherwise feel free to close.

**Comment by theofidry** [comment]
Not sure, I'm going to review it today

**Comment by theofidry** [comment]
@bamarni updated

**Comment by theofidry** [comment]
ping here as well. Much less urgent so no need to hurry, just wanna make sure you saw it :)

**Comment by bamarni** [comment]
Thanks

**Comment by bamarni** [comment]
Your plugin looks like a nice complement (eg. to install phpunit and similar tools), if you want to add a paragraph and more context about it I'll gladly merge it too.

**Pull request merged**
